### ISSUE TITLE
Getting information on column type

### ISSUE THREAD

**Issue by danielmk** [SFB1089/adamacs#11]
This issue is related to something me and @CBroz1 were just discussing on zoom. I am building GUIs and I want the GUI to figure out what kind of widget to use based on column type. If the column is a foreign key I would like to know the type of the table it is from (dj.Manual or dj.Lookup etc.). Another option would be to infer the widget type based on column content rather than type but I imagine that solution could slow down GUI loading as the system scales.
Right now my GUI is doing this to figure out how many widgets are need and how they should be named:

```
sub = subject.Subject()
sub.fetch().dtype.names
```

Any help on good practices to get more column information would be appreciated.

**Comment by CBroz1** [comment]
Hi @danielmk - This may help you get what you need: `__bases__` Thinh recommended it as a way of determining table type, and then you can build drop downs for only the dj.Lookup tables

![image](https://user-images.githubusercontent.com/9404707/140810888-0fab2ddb-0bb3-4fcb-bc19-41d46c63f3a0.png)
