### ISSUE TITLE
elements-imaging scan.py Equipment table cannot locate

### ISSUE THREAD

**Issue by danielmk** [SFB1089/adamacs#12]
I've been studying datajoint-elements to include it in adamacs. In element-calcium-imaging in scan.py the table `Scan` uses `Equipment` as a foreign key. I cannot find the `Equipment` table anywhere, is it part of datajoint-elements at all? Here is the scan.py file for reference:
https://github.com/datajoint/element-calcium-imaging/blob/main/element_calcium_imaging/scan.py

@CBroz1 maybe you have an idea where the `Equipment` table comes from?

**Comment by CBroz1** [comment]
Hi Daniel - We currently rely on the pipeline to provide an `Equipment` table, see [example workflow here](https://github.com/datajoint/workflow-calcium-imaging/blob/main/workflow_calcium_imaging/pipeline.py#L33)
