### ISSUE TITLE
adamacs `imaging` schema vs. `element_calcium_imaging.imaging`

### ISSUE THREAD

**Issue by CBroz1** [SFB1089/adamacs#14]
Are there pieces of the current `imaging` schema that differ from `element_calcium_imaging.imaging`? Or pieces of current `scan` schema that differ? Are there reasons not to directly import from the element or a fork thereof?

By version pinning in requirements (e.g., `element_calcium_imaging==0.1.0b0`), you could import a static version and occasionally assess if recent updates would be helpful (see [recent commit history](https://github.com/datajoint/element-calcium-imaging/commits/main))

**Comment by danielmk** [comment]
I am installing element-imaging from the fork I created with `element-calcium-imaging @ git+https://github.com/SFB1089/element-calcium-imaging.git@main` (see setup.py). THe fork is currently identical to the original.

This means that imaging.py is obsolete and should be replaced with element_calcium_imaging.imaging as installed from the fork.

I should do that tomorrow, kind of forgot about it actually.
