### ISSUE TITLE
Conflicting requirements 

### ISSUE THREAD

**Issue by CBroz1** [SFB1089/adamacs#20]
1. I previously added `ruamel` and `csv` to `requirements.txt`. This should just be `ruamel.yaml`. `csv` is part of Python core. See [this fork](https://github.com/CBroz1/adamacs/blob/main/requirements.txt)
2. `element-deeplabcut` had some issues in development with `numpy>1.20` so we version-locked in development. This conflicts with `element-calcium-imaging` requirements, as discussed [here](https://github.com/datajoint/element-interface/issues/27). I'm looking into this and will propose a solve shortly.

**Comment by danielmk** [comment]
Requirements are currently working.
